version: "3"

services:
  mongodb:
    image: mongo:5.0.4
    restart: always
    volumes: 
      - mongodb:/data/db
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3.9.10-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:6.2.6
    restart: always
    ports:
      - 6379:6379

  pgts:
    image: timescale/timescaledb:2.8.1-pg14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rightech
    volumes: 
      - pgts:/var/lib/postgresql/data
    ports:
      - 5432:5432

  minio:
    image: minio/minio:RELEASE.2023-01-25T00-19-54Z
    command: server --console-address ":9001" /storage
    restart: always
    volumes:
      - minio:/storage
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio12345

  ric-web:
    image: ric-web:2.29.2-rc1
    restart: always
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - 3000:3000
    env_file:
      - docker.env
    volumes:
     - "./user_modules:/user_modules"
     - "./node_modules:/node_modules"

volumes:
  mongodb:
  pgts:
  minio: