version: "3"

services:
  mongodb:
    image: mongo:5.0.4
    restart: always
    volumes: 
      - /data/db:/data/db
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3.9.10-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:6.2.6
    restart: always
    ports:
      - 6379:6379

  ric-web:
    image: ric-web:2.5.6-rc7
    restart: always
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - 3000:3000
    env_file:
      - docker.env
    volumes:
     - "./user_modules:/user_modules"
     - "./node_modules:/node_modules"