version: "3"

services:
  mongodb:
    image: mongo:5.0.4
    restart: always
    volumes: 
      - mongodb:/data/db
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3.9.10-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:6.2.6
    restart: always
    ports:
      - 6379:6379

  pgts:
    image: timescale/timescaledb:2.8.1-pg14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rightech
    volumes: 
      - pgts:/var/lib/postgresql/data
    ports:
      - 5432:5432

  ric-web:
    image: ric-web:2.11.1-rc2
    restart: always
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - 3000:3000
    env_file:
      - docker.env
    volumes:
     - "./user_modules:/user_modules"
     - "./node_modules:/node_modules"

volumes:
  mongodb:
  pgts: